[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "bf"
description = ""
readme = "README.md"
version = "0.1.0"
requires-python = "== 3.10.14"
dependencies = []

[project.optional-dependencies]
dev = [
    "mypy == 1.12.0",
    "ruff == 0.7.0",
]
